### ISSUE TITLE
Cannot pass custom `InputPos`

### ISSUE THREAD

**Issue by ferdinand-beyer** [strojure/parsesso#6]
I've tried to create a custom `InputPos` and pass it via the `:pos` option to `p/parse`. Unfortunately, the resulting positions are always `nil`.

I've tracked it down to the `:default` method of `init-pos`:

```clojure
(defmethod init-pos :default
  [{:keys [pos]} _]
  (when (keyword? pos)
    (throw (ex-info (str "Cannot init input position for: " pos) {}))
    pos))
```

The `when` should probably be an `if`, to use the passed `pos` if it is not a keyword.

Side question: Is there a recommended way to construct a `TextPos`, since `strojure.parsesso.impl.pos` is a private namespace? Alternatively, could we pass `:line` and `:col` options to initialize the `TextPos` with values other than 1? This is useful in a multi-pass scenario, when we want to pass a known position to a sub-parser (e.g. parsing a XML attribute value, where we already know the attribute node's position).

**Comment by serioga** [comment]
> I've tried to create a custom InputPos and pass it via the :pos option to p/parse. Unfortunately, the resulting positions are always nil.

Can you provide an illustrating code fragment?

**Comment by serioga** [comment]
> could we pass :line and :col options to initialize the TextPos with values other than 1?

yes, I will add initialization of values from options of `:text` pos

**Comment by serioga** [comment]
Looks like current implementation works only with keyword pos extendable via adding `pos/init-pos` methods.
So docstring is misleading about this.
I think its OK to have only one way to extend without direct usage of `InputPos` on user side.
Let's try to write code you need, and see.

**Comment by ferdinand-beyer** [comment]
> Can you provide an illustrating code fragment?

Sure, here is an example:

```clojure
(require '[strojure.parsesso.parser :as p]
         '[strojure.parsesso.impl.pos :as pos])

(p/parse (p/get-state :pos) "" {:pos :text}) ; => {:tab 8, :line 1, :col 1}
(p/parse (p/get-state :pos) "" {:pos (pos/->TextPos 8 7 13)}) ; => nil
```

So I wanted to tell the parser not to start at 1,1, but 7,13. As you can see, the position is reported as `nil`.

The `init-pos` sees the `TextPos`, checks for an unsupported keyword, and returns `nil` because of the `when`. I'm pretty sure if we change the `when` to `if`, this would work, as `init-pos` would return the `TextPos` unchanged.

Ideally, I would not need to construct the `TextPos` myself, as this requires using the `impl` namespace. Instead, this would work for me:

```clojure
(p/parse (p/get-state :pos) "" {:pos :text, :line 7, :col 13}) ; => {:tab 8, :line 7, :col 13}
```

Should be quite easy, as the `init-pos` method for `:text` can look for the `:line` and `:col` options.

Let me know if it would help if I wrote a PR!

**Comment by ferdinand-beyer** [comment]
I currently work around it by providing a custom method:

```clojure
(defmethod pos/init-pos ::text
  [{:keys [tab line col] :or {tab 8, line 1, col 1}} _]
  (pos/TextPos. tab line col))

(p/parse (p/get-state :pos) "" {:pos ::text, :line 7, :col 13}) ; => {:tab 8, :line 7, :col 13}
```

**Comment by serioga** [comment]
@ferdinand-beyer thank you for report 🙇

**Comment by ferdinand-beyer** [comment]
Thanks for improving this!

Small nitpick for a rainy day: You forgot to update the `:arglists` -- they contain `tab` but not `line` and `col` :)

```clojure
  {:arglists '([p input]
               [p input {:keys [pos, tab, user-state] :as options}])}
```
