### ISSUE TITLE
Allow destructuring in `p/for`

### ISSUE THREAD

**Issue by ferdinand-beyer** [strojure/parsesso#8]
The `for` macro asserts that the binding form is a symbol:

```clojure
(assert (symbol? sym) (str "Requires symbol for binding name: " sym))
```

This restriction seems unnecessary, and prevents users from using destructuring:

```clojure
(p/parse (p/for [[x & xs] (p/*many char/number?)]
           (p/result {:first x, :rest xs}))
         "12345")
```

Maybe we can remove the `assert`?

**Comment by serioga** [comment]
Removed the `assert` :-)
